name: Mirror to GitLab

on:
  push:
    branches:
      - main  

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire commit history

      - name: Push branches and tags to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.huma-num.fr/ecrinum/anthologia/ner-anthologia.git
          git push gitlab --branches
          git push gitlab --tags
